version: '3'
services:
  reverseproxy:
    build: ./
    image: reverseproxy
    ports:
      - 8080:8080
      - 8081:8081
    
  nginx:
    depends_on:
      - reverseproxy
    image: nginx:alpine
    restart: always
  
  apache:
    depends_on:
      - reverseproxy
    image: httpd:alpine
    restart: always
      